name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: lsmoura/eslint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}